version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - api

  api:
    build: .
    container_name: ${API_CONTAINER}
    command: python app.py
    volumes:
      - ./downloads:/app/downloads
    depends_on:
      - redis

  worker:
    build: .
    container_name: ${wORKER_CONTAINER}
    command: python worker.py
    volumes:
      - ./downloads:/app/downloads
    depends_on:
      - redis

  redis:
    image: redis:7